name: Build and Upload nightly game builds

on:
  workflow_dispatch:
    inputs:
      build-defines:
        type: string
        description: Build defines to use
        default: '-DGITHUB_BUILD'
      save-artifact:
        type: boolean
        description: Save the build artifact to Github Actions (sends to itch otherwise)
        default: false
  push:
    paths-ignore:
    - '**/Dockerfile'
    - '.github/workflows/build-docker-image.yml'

jobs:

  build-game-on-host:
    strategy:
      matrix:
        include:
        - target: linux
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Make git happy
      run: |
        git config --global --replace-all safe.directory $GITHUB_WORKSPACE
    - name: Get checkout token
      uses: actions/create-github-app-token@v1
      id: app_token
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.APP_PEM }}
        owner: ${{ github.repository_owner }}
    - name: Checkout repo
      uses: funkincrew/ci-checkout@v6
      with:
        submodules: 'recursive'
        token: ${{ steps.app_token.outputs.token }}
        persist-credentials: false
    - name: Setup build environment
      uses: ./.github/actions/setup-haxe
      with:
        gh-token: ${{ steps.app_token.outputs.token }}
    - name: Setup NDK
      uses: nttld/setup-ndk@main
      id: setup-ndk
      with:
        ndk-version: r21e
    - name: Setup HXCPP dev commit
      run: |
        cd .haxelib/hxcpp/git/tools/hxcpp
        haxe compile.hxml
        cd ../../../../..
    - name: Mobile Configure
      run: |
        haxelib run lime config ANDROID_SDK $ANDROID_HOME
        haxelib run lime config ANDROID_NDK_ROOT ${{ steps.setup-ndk.outputs.ndk-path }}
        haxelib run lime config JAVA_HOME $JAVA_HOME_11_X64
        haxelib run lime config ANDROID_SETUP true
    - name: Build game
      run: |
        haxelib run lime build ${{ matrix.target }} -v -release --times ${{ github.event.inputs.build-defines }}
      timeout-minutes: 120
    - name: Save build artifact to Github Actions
      if: ${{ github.event.inputs.save-artifact }}
      uses: actions/upload-artifact@main
      with:
        name: build-${{ matrix.target }}
        path: export/release/${{matrix.target}}/bin/


    - name: Upload build artifacts
      uses: ./.github/actions/upload-itch
      with:
        butler-key: ${{ secrets.BUTLER_API_KEY}}
        target: ${{ matrix.target }}
  
